---
# tasks file for osp-facts
- name: Fetch Instance Info
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
  register: result

- name: Remove floating IP to db
  os_floating_ip:
    cloud: ospcloud
    state: absent
    server: db
    key_name: ansible_ssh

- name: Remove a server instance db
  os_server:
    cloud: ospcloud
    name: db
    state: absent
    key_name: ansible_ssh
