---
# tasks file for osp-facts
- name: Fetch Instance Info
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
  register: result

# Detach a floating IP address from a server
- name: Remove floating ip for  "{{ instance_name }}"
  os_floating_ip:
    cloud: ospcloud
    state: absent
    server: "{{ instance_name }}"
  ignore_errors: yes

# Deletes an instance via its ID
- name: Remove an instance "{{ instance_name }}"
  os_server:
    name: "{{ instance_name }}"
    state: absent
