---
# tasks file for osp-facts
- name: Fetch Instance Info
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
  register: result

# Detach a floating IP address from a server
- os_floating_ip:
    cloud: ospcloud
    state: absent
#    loating_ip_address: 203.0.113.2
    server: "{{ instance_name }}"
    ignore_errors: yes

# Deletes an instance via its ID
- name: remove an instance
  os_server:
    name: "{{ instance_name }}"
    state: absent
