- hosts: workstation
  become: yes

  tasks:
##Deletes Fronend Instance
  - name: Create frontend instance
    include_role:
       name: osp-instance-delete
       vars_from: frontend.yaml
##Deletes App1 server 
  - name: Create apps instance
    include_role:
       name: osp-instance-delete
       vars_from: apps.yaml
##Deletes App2 server
  - name: Create appdbs instance
    include_role:
       name: osp-instance-delete
       vars_from: appdbs.yaml
       
##Deletes Additional server
#  - name: Create Additional instance
#    include_role:
#       name: osp-instance-delete
# Prepare vars for Addtional server to remove
#       vars_from: Additional.yaml
