- hosts: workstation
  become: yes

  tasks:
##Deletes Fronend Instance
  - name: Create frontend instance
    include_role:
       name: osp-instance-delete
       vars_from: frontend.yaml
##Deletes App1 server 
  - name: Create app1 instance
    include_role:
       name: osp-instance-delete
       vars_from: app1.yaml
##Deletes App2 server
  - name: Create app2 instance
    include_role:
       name: osp-instance-delete
       vars_from: app2.yaml
##Deletes DB server
  - name: Create db instance
    include_role:
       name: osp-instance-delete
vars_from: db.yaml
