- hosts: tag_AnsibleGroup_frontends
  gather_facts: false
  
  tasks:
  
  - name: Curl website
    uri:
      url: "http://{{ inventory_hostname }}"
      return_content: yes
    register: webpage
  - debug: var=webpage
  
  - name: Fail if 'MitziCom Home Page' is not in the page content
    fail:
    when: "'MitziCom Home Page' not in webpage.stdout"
