---
- hosts: workstation
  become: yes
    
  tasks:
    - name: Start a server insance
      os_server_action:
        cloud: ospcloud
        action: start
        server: "{{ item }}"
        timeout: 100
      loop:
        - frontend
        - app1
        - app2
        - appdbs
