- hosts: workstation
  become: yes

  tasks:
##Create Fronend Instance
  - name: Create frontend instance
    include_role:
       name: osp-servers
       vars_from: frontend.yaml
##Create App1 server 
  - name: Create apps instance
    include_role:
       name: osp-servers
       vars_from: apps.yaml
##Create App2 server
  - name: Create appdbs instance
    include_role:
       name: osp-servers
       vars_from: appdbs.yaml

##Create Additional server
#  - name: Create Additional instance
#    include_role:
#       name: osp-servers
# Prepare vars for additional server
#       vars_from: Aditional.yaml 

## Alternate Method to create dynmaic inventory
#  - name: Gather facts
#    include_role: 
#       name: osp-facts
#    tags:
#- test_inventory
