- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
      cloud: ospcloud
      server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
  - name: Curl website
    uri:
      url: "http://{{item.public_v4}}"
      return_content: yes
    with_items:
      - "{{ openstack_info.ansible_facts.openstack_servers }}"
    register: webpage
  
  - name: Fail if 'Welcome to MitziCom' is not in the page content
    fail:
    when: "'Welcome to MitziCom' not in webpage.results[0].content"
    tags:
      - osp.smoke
