- hosts: workstation
  gather_facts: true
  become: yes
  roles:
    - name: osp-facts

# Setup front-end load balancer tier "{{ ansible_env.USER }}"


- name: setup load-balancer tier "{{ ansible_env.USER }}"
  hosts: frontend
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
