- hosts: tag_AnsibleGroup_frontends
  gather_facts: true
  tasks:
  
  - name: Curl website
    uri:
      url: "http://{{ansible_default_ipv4.address}}"
      return_content: yes
   
    register: webpage
  
  - name: Fail if 'MitziCom Home Page' is not in the page content
    fail:
    when: "'MitziCom Home Page' not in webpage.results[0].content"
