---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    cloud: ospcloud
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    image: rhel-guest
    meta: "group: {{ item.meta_group }},deployment_name: {{ item.meta_deployment_name }}"
    flavor: m2.small
    security_groups: "{{ item.security_group }}"
    key_name: ansible_ssh
    wait: yes
    nics:
    - net-name: int_network
  loop: "{{ frontend }}"

- name: Add floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: yes
    server: "{{ item.name }}"
    network: ext_network
    wait: true
    timeout: 180
  loop: "{{ frontend }}" 

- name: Wait for server to be available
  wait_for:
    host: "{{ item.name }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600
  delegate_to: "{{ item.state }}"
  loop: "{{ frontend }}"
