- name: Create Homework Assignment project 
# Use tower module or tower-cli to create Ansible Tower project. Name of the project is specifed in ./vars/main.yml
  command: |
    tower-cli project create --name "{{ proj_name }}" --description "MitziCom AWS project" --organization "{{org_name}}" --scm-type "git" --scm-url "https://github.com/PawelNikodem/ansible_advance_homework"

- name: Add public key for cloud-user
  command: |
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTCYfp/LvJHpyMqZBeXoX/jHz/LB4yAeRBMYLf3V/kopcIetQQHYIkgW96LB9CmQABX9heoopsDK8tj5IZgz//dPqfYapm+S4mz8jIOFvIwmUle6iM2KdBvMGqIBKiURVoTwQZZMoWzZEqmaHFrRuNrZCDUJ8B3LmNBqp3UQtnYUuG2Vtg/q94Wqlv7nGiBJ/bT0HhPjrsFGXJs29F354rK3Xp9KeKO9RB2PYNgIJ22KFNOZ3IV67I5bd2uJQXHEuQYqAenHh/cIt1GicOVGHKr9RQOngz4093/tuVfiwhIyKZVWu4Xm3G8x6v9nyg4ifi5XSBNvXBCuXSdivv+yd" >> /home/cloud-user/.ssh/authorized_keys

- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    ssh_key_data: "/root/.ssh/openstack.pem"
    username: cloud-user

- name: Create Inventory
  command: |
    tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"

- name: Create Group in static inventory 
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name {{group_name}}

- name: Add workstation host in tower_inventory 
  command: |
    tower-cli host create --inventory "{{static_inventory_name}}" --name "{{host_name}}"

- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"


- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    tower_verify_ssl: no
    ssh_key_data: /root/.ssh/mykey.pem
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

